type Language = "ar" | "en"

const MESSAGES: Record<Language, Record<string, string>> = {
  ar: {
    "lang.ar": "العربية",
    "lang.en": "English",

    "nav.dashboard": "لوحة التحكم",
    "nav.customers": "العملاء",
    "nav.all_sections": "كل الأقسام",
    "nav.raw_materials": "المواد الخام",
    "nav.fragrances": "العطور",
    "nav.colors": "الألوان",
    "nav.customer_portal": "بوابة العملاء",
    "nav.sections": "الأقسام",
    "nav.welcome": "أهلاً",
    "nav.user": "المستخدم",
    "nav.logout": "تسجيل الخروج",

    "auth.crm_system": "نظام إدارة علاقات العملاء",
    "auth.manage_all": "إدارة جميع جوانب عملك والعملاء من مكان واحد",
    "auth.admin_controls": "تحكم كامل في نظام العمليات",
    "auth.customer_tracks": "تتبع أوامرك وحساباتك",
    "auth.history": "سجل كامل من كل معاملاتك",
    "auth.login": "تسجيل الدخول",
    "auth.enter_details": "أدخل بيانات حسابك",
    "auth.email": "عنوان البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.create_account": "إنشاء حساب",
    "auth.loading": "جاري التحميل...",
    "auth.default_admin": "المسؤول الافتراضي",
    "auth.backend_missing": "خادم API غير متصل. يرجى التحقق من اتصالك.",

    "register.new_customer": "عميل جديد",
    "register.follow_prices": "تابع أسعار منتجاتنا وقارن الأسعار",
    "register.create_account": "إنشاء حساب",
    "register.saved_in_dashboard": "سيتم حفظ بياناتك في لوحة التحكم",
    "register.full_name": "الاسم الكامل",
    "register.phone": "رقم الهاتف",
    "register.back_to_login": "العودة لتسجيل الدخول",
    "register.created": "تم إنشاء حسابك. يرجى تسجيل الدخول.",

    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.reset": "إعادة تعيين",
    "common.add": "إضافة",
    "common.save_changes": "حفظ التغييرات",
    "common.select_item": "اختر عنصراً",
    "common.search": "بحث",
    "common.previous": "السابق",
    "common.next": "التالي",
    "common.price": "السعر",
    "common.name": "الاسم",
    "common.notes": "ملاحظات",
    "common.no_data": "لا توجد بيانات",
    "common.currency": "ج.م",
    "common.product": "المنتج",
    "common.category": "القسم",
    "common.quantity": "الكمية",
    "common.total": "الإجمالي",
    "common.date": "التاريخ",
    "common.back": "رجوع",
    "common.print": "طباعة",
    "common.details": "التفاصيل",
    "common.actions": "الإجراءات",
    "common.email": "عنوان البريد الإلكتروني",
    "common.phone": "الهاتف",
    "common.company": "الشركة",
    "common.address": "العنوان",
    "common.unit": "الوحدة",
    "common.view": "عرض",
    "common.confirm_delete_item": "هل أنت متأكد من حذف هذا العنصر؟",
    "common.saved_success": "تم الحفظ بنجاح",
    "common.added_success": "تم الإضافة بنجاح",
    "common.no_results": "لا توجد نتائج",

    "home.title": "الأقسام الرئيسية",
    "home.raw_materials": "المواد الخام",
    "home.fragrances": "العطور",
    "home.colors": "الألوان",
    "home.products_count": "منتج",
    "home.no_raw_materials": "لا توجد مواد",
    "home.no_fragrances": "لا توجد عطور",
    "home.no_colors": "لا توجد ألوان",

    "kpi.customers": "عدد العملاء",
    "kpi.items_total": "إجمالي المستحق",
    "kpi.payments_total": "إجمالي الدفعات",
    "kpi.balance_total": "إجمالي الأرصدة",
    "kpi.top_debtors": "أكثر العملاء المدينين",
    "kpi.recent": "آخر المعاملات",
    "kpi.customer": "العميل",
    "kpi.withdrawn": "إجمالي المستحق",
    "kpi.paid": "المدفوع",
    "kpi.balance": "الرصيد",
    "kpi.type": "النوع",
    "kpi.details": "التفاصيل",
    "kpi.value": "القيمة",
    "kpi.date": "التاريخ",
    "kpi.item_movement": "حركة المنتج",
    "kpi.order": "طلب",
    "kpi.payment": "الدفع",

    "ledger.title": "دفتر العميل",
    "ledger.current_customer": "العميل الحالي",
    "ledger.select_customer": "اختر عميل أولاً",
    "ledger.total_items": "إجمالي البضائع",
    "ledger.total_paid": "إجمالي المدفوع",
    "ledger.balance_due": "الرصيد",
    "ledger.add_movement": "إضافة حركة منتج",
    "ledger.category": "القسم",
    "ledger.item_name": "اسم البند",
    "ledger.quantity": "الكمية",
    "ledger.unit": "الوحدة",
    "ledger.unit_price": "سعر الوحدة",
    "ledger.notes": "ملاحظات",
    "ledger.save_movement": "حفظ الحركة",
    "ledger.add_payment": "إضافة دفع",
    "ledger.amount": "المبلغ",
    "ledger.payment_method": "طريقة الدفع",
    "ledger.save_payment": "حفظ الدفع",
    "ledger.movements": "حركات البضائع",
    "ledger.payments": "الدفعات",
    "ledger.item": "البند",
    "ledger.total": "الإجمالي",
    "ledger.date": "التاريخ",
    "ledger.no_movements": "لا توجد حركات",
    "ledger.no_payments": "لا توجد دفعات",
    "ledger.category.raw_material": "مواد خام",
    "ledger.category.fragrance": "عطور",
    "ledger.category.color": "ألوان",

    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "إدارة العملاء والمنتجات والتحديثات والطلبات",
    "dashboard.updates": "تحديثات الموقع",
    "dashboard.publish": "نشر التحديث",
    "dashboard.orders": "طلبات العملاء",
    "dashboard.product": "المنتج",
    "dashboard.status": "الحالة",
    "dashboard.update_title": "عنوان التحديث",
    "dashboard.update_content": "محتوى التحديث",
    "dashboard.customer": "العميل",
    "dashboard.category": "القسم",
    "dashboard.total": "الإجمالي",
    "dashboard.actions": "الإجراءات",

    "customers.title": "إدارة العملاء",
    "customers.subtitle": "إدارة سجلات العملاء",
    "customers.saved": "تم حفظ العميل بنجاح",
    "customers.deleted": "تم حذف العميل",
    "customers.pick_customer": "اختر عميل من الجدول",
    "customers.confirm_delete": "هل تريد حذف هذا العميل؟",

    "customer.form.title": "بيانات العميل",
    "customer.form.name": "اسم العميل",
    "customer.form.phone": "الهاتف",
    "customer.form.email": "البريد الإلكتروني",
    "customer.form.company": "الشركة",
    "customer.form.address": "العنوان",
    "customer.form.notes": "ملاحظات",
    "customer.form.create": "إضافة عميل",
    "customer.form.update": "تحديث العميل",

    "customer.table.title": "قائمة العملاء",
    "customer.table.search_placeholder": "ابحث عن العميل أو الهاتف",
    "customer.table.id": "#",
    "customer.table.name": "الاسم",
    "customer.table.phone": "الهاتف",
    "customer.table.email": "البريد الإلكتروني",
    "customer.table.balance": "الرصيد",
    "customer.table.actions": "الإجراءات",
    "customer.table.ledger": "الدفتر",
    "customer.table.page": "صفحة",
    "customer.table.no_customers": "لا توجد عملاء",
    "customer.account.title": "حساب العميل",
    "customer.account.subtitle": "كل بيانات العميل وطلباته ومدفوعاته في صفحة واحدة",
    "customer.account.profile": "بيانات العميل",
    "customer.account.total_charges": "إجمالي المستحق",
    "customer.account.approved_orders": "الطلبات المعتمدة",
    "customer.account.pending_orders": "طلبات قيد الانتظار",
    "customer.account.credit_balance": "رصيد دائن",
    "customer.account.order_count": "عدد الطلبات",
    "customer.account.orders": "طلبات العميل",
    "customer.account.manual_entries": "الحركات اليدوية",
    "customer.account.transactions": "سجل المعاملات",
    "customer.account.empty_orders": "لا توجد طلبات لهذا العميل",
    "customer.account.empty_transactions": "لا توجد معاملات مسجلة",

    "catalog.title": "الأقسام",
    "catalog.subtitle": "إدارة المواد الخام والعطور والألوان",
    "catalog.raw_title": "المواد الخام",
    "catalog.raw_sub": "المكونات الأساسية المستخدمة في المنظفات",
    "catalog.frag_title": "العطور",
    "catalog.frag_sub": "خيارات العطور المتاحة",
    "catalog.color_title": "الألوان",
    "catalog.color_sub": "إضافات الألوان المستخدمة في المنتجات",
    "catalog.add_raw": "إضافة مادة خام",
    "catalog.add_frag": "إضافة عطر",
    "catalog.add_color": "إضافة لون",
    "catalog.raw_name": "اسم المادة الخام",
    "catalog.frag_name": "اسم العطر",
    "catalog.color_name": "اسم اللون",

    "section.manage": "إدارة",
    "section.subtitle": "إضافة وتعديل المنتجات حسب الاسم والسعر",
    "section.not_found": "القسم غير موجود",
    "section.products": "منتجات القسم",
    "section.no_items": "لا توجد عناصر في هذا القسم حتى الآن",
    "section.add_item": "إضافة عنصر",
    "section.edit_item": "تعديل العنصر",
    "section.manage_category": "إدارة",
    "section.unknown": "غير معروف",

    "portal.title": "بوابة العملاء",
    "portal.subtitle": "آخر التحديثات والأسعار والطلبات",
    "portal.latest_updates": "آخر التحديثات",
    "portal.no_updates": "لا توجد تحديثات حتى الآن",
    "portal.new_order": "إنشاء طلب جديد",
    "portal.product": "المنتج",
    "portal.category": "القسم",
    "portal.quantity": "الكمية",
    "portal.unit_price": "سعر الوحدة",
    "portal.notes": "ملاحظات",
    "portal.add_item": "إضافة صنف للطلب",
    "portal.selected_items": "الأصناف المختارة",
    "portal.empty_selected_items": "لم تتم إضافة أي أصناف بعد",
    "portal.selection_help": "حدد الأصناف المطلوبة من القائمة ثم اكتب الكمية أمام كل صنف بسهولة.",
    "portal.clear_selection": "مسح الاختيار",
    "portal.order_total": "إجمالي الطلب",
    "portal.order_items_required": "أضف صنفًا واحدًا على الأقل إلى الطلب",
    "portal.submit_order": "تقديم الطلب",
    "portal.catalog_prices": "أسعار الكتالوج",
    "portal.my_orders": "طلباتي",
    "portal.order_submitted": "تم تقديم الطلب بنجاح",
    "portal.select_product": "اختر منتج",
    "portal.price_label": "السعر",
    "portal.actions": "الإجراءات",

    "order.details_title": "تفاصيل الطلب",
    "order.details_subtitle_admin": "راجع بيانات الطلب وأدر حالته",
    "order.details_subtitle_customer": "تتبع طلبك ومراجعة تفاصيله",
    "order.customer_information": "معلومات العميل",
    "order.order_information": "معلومات الطلب",
    "order.order_number": "رقم الطلب",
    "order.items_count": "عدد الأصناف",
    "order.invoice_number": "رقم الفاتورة",
    "order.created_at": "تاريخ الطلب",
    "order.approval_date": "تاريخ الموافقة",
    "order.invoice_issued_at": "تاريخ الفاتورة",
    "order.update_status": "تحديث الحالة",
    "order.save_status": "حفظ الحالة",
    "order.view_invoice": "عرض الفاتورة",
    "order.order_notes": "ملاحظات الطلب",
    "order.no_notes": "لا توجد ملاحظات",
    "order.invoice_title": "فاتورة الطلب",
    "order.invoice_subtitle_admin": "نسخة إدارية من الفاتورة",
    "order.invoice_subtitle_customer": "نسخة موافقة عليها من الفاتورة",
    "order.invoice_unavailable": "الفاتورة غير متاحة حتى يتم الموافقة على الطلب",
    "order.invoice_ready": "الفاتورة جاهزة",
    "order.back_to_dashboard": "العودة إلى لوحة التحكم",
    "order.back_to_portal": "العودة إلى البوابة",
    "order.back_to_order": "العودة إلى الطلب",
    "order.print_invoice": "طباعة الفاتورة",
    "order.download_invoice": "تحميل PDF",

    "status.pending": "قيد الانتظار",
    "status.approved": "موافق عليه",
    "status.rejected": "مرفوض",
    "status.completed": "مكتمل",
    "status.recorded": "مسجل"
  },
  en: {
    "lang.ar": "Arabic",
    "lang.en": "English",

    "nav.dashboard": "Dashboard",
    "nav.customers": "Customers",
    "nav.all_sections": "All Sections",
    "nav.raw_materials": "Raw Materials",
    "nav.fragrances": "Fragrances",
    "nav.colors": "Colors",
    "nav.customer_portal": "Customer Portal",
    "nav.sections": "Sections",
    "nav.welcome": "Welcome",
    "nav.user": "User",
    "nav.logout": "Logout",

    "auth.crm_system": "CRM System",
    "auth.manage_all": "Manage customers, prices and orders in one place.",
    "auth.admin_controls": "Admin controls dashboard.",
    "auth.customer_tracks": "Customer tracks updates and prices.",
    "auth.history": "Each account has its own order history.",
    "auth.login": "Login",
    "auth.enter_details": "Enter your account details.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.create_account": "Create account",
    "auth.loading": "Loading...",
    "auth.default_admin": "Default admin",
    "auth.backend_missing": "Backend API route is missing. Restart backend with latest code.",

    "register.new_customer": "New Customer",
    "register.follow_prices": "Create your own account to follow prices and place orders.",
    "register.create_account": "Create Account",
    "register.saved_in_dashboard": "Your data will be saved in the admin dashboard.",
    "register.full_name": "Full Name",
    "register.phone": "Phone",
    "register.back_to_login": "Back to login",
    "register.created": "Account created. You can login now.",

    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.reset": "Reset",
    "common.add": "Add",
    "common.save_changes": "Save changes",
    "common.select_item": "Select item",
    "common.search": "Search",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.price": "Price",
    "common.name": "Name",
    "common.notes": "Notes",
    "common.no_data": "No data",
    "common.currency": "EGP",
    "common.product": "Product",
    "common.category": "Category",
    "common.quantity": "Quantity",
    "common.total": "Total",
    "common.date": "Date",
    "common.back": "Back",
    "common.print": "Print",
    "common.details": "Details",
    "common.actions": "Actions",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.company": "Company",
    "common.address": "Address",
    "common.unit": "Unit",
    "common.view": "View",
    "common.confirm_delete_item": "Delete this item?",
    "common.saved_success": "Saved successfully",
    "common.added_success": "Added successfully",
    "common.no_results": "No results",

    "home.title": "Products by Sections",
    "home.raw_materials": "Raw Materials",
    "home.fragrances": "Fragrances",
    "home.colors": "Colors",
    "home.products_count": "products",
    "home.no_raw_materials": "No raw materials found",
    "home.no_fragrances": "No fragrances found",
    "home.no_colors": "No colors found",

    "kpi.customers": "Customers Count",
    "kpi.items_total": "Total Charges",
    "kpi.payments_total": "Total Paid",
    "kpi.balance_total": "Total Balance",
    "kpi.top_debtors": "Top Debtors",
    "kpi.recent": "Recent Movements",
    "kpi.customer": "Customer",
    "kpi.withdrawn": "Charges",
    "kpi.paid": "Paid",
    "kpi.balance": "Balance",
    "kpi.type": "Type",
    "kpi.details": "Details",
    "kpi.value": "Value",
    "kpi.date": "Date",
    "kpi.item_movement": "Item Movement",
    "kpi.order": "Order",
    "kpi.payment": "Payment",

    "ledger.title": "Customer Ledger",
    "ledger.current_customer": "Current customer",
    "ledger.select_customer": "Select a customer first",
    "ledger.total_items": "Total Items",
    "ledger.total_paid": "Total Paid",
    "ledger.balance_due": "Balance Due",
    "ledger.add_movement": "Add Product Movement",
    "ledger.category": "Category",
    "ledger.item_name": "Item Name",
    "ledger.quantity": "Quantity",
    "ledger.unit": "Unit",
    "ledger.unit_price": "Unit Price",
    "ledger.notes": "Notes",
    "ledger.save_movement": "Save Movement",
    "ledger.add_payment": "Add Payment",
    "ledger.amount": "Amount",
    "ledger.payment_method": "Payment Method",
    "ledger.save_payment": "Save Payment",
    "ledger.movements": "Product Movements",
    "ledger.payments": "Payments",
    "ledger.item": "Item",
    "ledger.total": "Total",
    "ledger.date": "Date",
    "ledger.no_movements": "No movements",
    "ledger.no_payments": "No payments",
    "ledger.category.raw_material": "Raw Materials",
    "ledger.category.fragrance": "Fragrances",
    "ledger.category.color": "Colors",

    "dashboard.title": "Admin Dashboard",
    "dashboard.subtitle": "Manage customers, products, updates and orders",
    "dashboard.updates": "Site Updates",
    "dashboard.publish": "Publish update",
    "dashboard.orders": "Customer Orders",
    "dashboard.product": "Product",
    "dashboard.status": "Status",
    "dashboard.update_title": "Update title",
    "dashboard.update_content": "Update content",
    "dashboard.customer": "Customer",
    "dashboard.category": "Category",
    "dashboard.total": "Total",
    "dashboard.actions": "Actions",

    "customers.title": "Customers & Accounts",
    "customers.subtitle": "Manage customer records",
    "customers.saved": "Customer saved successfully",
    "customers.deleted": "Customer deleted",
    "customers.pick_customer": "Select a customer from table",
    "customers.confirm_delete": "Delete this customer?",

    "customer.form.title": "Customer Data",
    "customer.form.name": "Customer Name",
    "customer.form.phone": "Phone",
    "customer.form.email": "Email",
    "customer.form.company": "Company",
    "customer.form.address": "Address",
    "customer.form.notes": "Notes",
    "customer.form.create": "Add Customer",
    "customer.form.update": "Update Customer",

    "customer.table.title": "Customers List",
    "customer.table.search_placeholder": "Search by name or phone",
    "customer.table.id": "#",
    "customer.table.name": "Name",
    "customer.table.phone": "Phone",
    "customer.table.email": "Email",
    "customer.table.balance": "Balance",
    "customer.table.actions": "Actions",
    "customer.table.ledger": "Ledger",
    "customer.table.page": "Page",
    "customer.table.no_customers": "No customers found",
    "customer.account.title": "Customer Account",
    "customer.account.subtitle": "Full customer data, orders, payments and balance in one place",
    "customer.account.profile": "Customer Profile",
    "customer.account.total_charges": "Total Charges",
    "customer.account.approved_orders": "Approved Orders",
    "customer.account.pending_orders": "Pending Orders",
    "customer.account.credit_balance": "Credit Balance",
    "customer.account.order_count": "Orders Count",
    "customer.account.orders": "Customer Orders",
    "customer.account.manual_entries": "Manual Entries",
    "customer.account.transactions": "Transactions",
    "customer.account.empty_orders": "No orders for this customer",
    "customer.account.empty_transactions": "No transactions recorded",

    "catalog.title": "Catalog Sections",
    "catalog.subtitle": "Manage raw materials, fragrances and colors",
    "catalog.raw_title": "Raw Materials",
    "catalog.raw_sub": "Core ingredients used in detergents",
    "catalog.frag_title": "Fragrances",
    "catalog.frag_sub": "Available fragrance options",
    "catalog.color_title": "Colors",
    "catalog.color_sub": "Color additives used in products",
    "catalog.add_raw": "Add raw material",
    "catalog.add_frag": "Add fragrance",
    "catalog.add_color": "Add color",
    "catalog.raw_name": "Raw material name",
    "catalog.frag_name": "Fragrance name",
    "catalog.color_name": "Color name",

    "section.manage": "Manage",
    "section.subtitle": "Add and edit products by name and price",
    "section.not_found": "Category not found",
    "section.products": "Section Products",
    "section.no_items": "No items in this section yet",
    "section.add_item": "Add item",
    "section.edit_item": "Edit item",
    "section.manage_category": "Manage",
    "section.unknown": "Unknown",

    "portal.title": "Customer Portal",
    "portal.subtitle": "Latest updates, prices and orders",
    "portal.latest_updates": "Latest Updates",
    "portal.no_updates": "No updates yet",
    "portal.new_order": "Create New Order",
    "portal.product": "Product",
    "portal.category": "Category",
    "portal.quantity": "Quantity",
    "portal.unit_price": "Unit Price",
    "portal.notes": "Notes",
    "portal.add_item": "Add item to order",
    "portal.selected_items": "Selected items",
    "portal.empty_selected_items": "No items added yet",
    "portal.selection_help": "Pick the products you want, then adjust the quantity beside each item.",
    "portal.clear_selection": "Clear selection",
    "portal.order_total": "Order total",
    "portal.order_items_required": "Add at least one item to the order",
    "portal.submit_order": "Submit order",
    "portal.catalog_prices": "Catalog Prices",
    "portal.my_orders": "My Orders",
    "portal.order_submitted": "Order submitted successfully",
    "portal.select_product": "Select product",
    "portal.price_label": "Price",
    "portal.actions": "Actions",

    "order.details_title": "Order Details",
    "order.details_subtitle_admin": "Review order data and manage its status",
    "order.details_subtitle_customer": "Track your order and review its details",
    "order.customer_information": "Customer Information",
    "order.order_information": "Order Information",
    "order.order_number": "Order Number",
    "order.items_count": "Items Count",
    "order.invoice_number": "Invoice Number",
    "order.created_at": "Order Date",
    "order.approval_date": "Approval Date",
    "order.invoice_issued_at": "Invoice Date",
    "order.update_status": "Update Status",
    "order.save_status": "Save Status",
    "order.view_invoice": "View Invoice",
    "order.order_notes": "Order Notes",
    "order.no_notes": "No notes",
    "order.invoice_title": "Order Invoice",
    "order.invoice_subtitle_admin": "Admin invoice copy",
    "order.invoice_subtitle_customer": "Your approved invoice copy",
    "order.invoice_unavailable": "Invoice is not available until the order is approved",
    "order.invoice_ready": "Invoice ready",
    "order.back_to_dashboard": "Back to dashboard",
    "order.back_to_portal": "Back to portal",
    "order.back_to_order": "Back to order",
    "order.print_invoice": "Print Invoice",
    "order.download_invoice": "Download PDF",

    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.completed": "Completed",
    "status.recorded": "Recorded"
  }
}

export function useLang() {
  const language = useState<Language>("app_lang", () => "ar")
  const initialized = useState<boolean>("app_lang_initialized", () => false)

  function isValidLanguage(value: string | null): value is Language {
    return value === "ar" || value === "en"
  }

  function setLanguage(next: Language) {
    language.value = next
    if (process.client) {
      localStorage.setItem("app_lang", next)
    }
  }

  function toggleLanguage() {
    setLanguage(language.value === "ar" ? "en" : "ar")
  }

  function initLanguage() {
    if (initialized.value) return
    initialized.value = true

    if (process.client) {
      const saved = localStorage.getItem("app_lang")
      if (isValidLanguage(saved)) {
        language.value = saved
      } else {
        language.value = "ar"
      }
    }
  }

  function t(key: string) {
    return MESSAGES[language.value]?.[key] || MESSAGES.ar[key] || key
  }

  const isRtl = computed(() => language.value === "ar")

  return {
    language,
    isRtl,
    initLanguage,
    setLanguage,
    toggleLanguage,
    t
  }
}

